POST http://localhost:3000/file-upload
Content-type: multipart/form-data; boundary=test-file-upload

--test-file-upload
Content-Disposition: form-data; name="file"; filename="test.txt"

< test.txt
--test-file-upload--