# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: supermarmot
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  deploymentBucket:
    name: tmd-genai1-students13
  environment:
    USERS_TABLE: ${self:service}-users-${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt UsersTable.Arn

resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:service}-users-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  getUser:
    handler: handler.getUser
    # The configuration warning "unsupported function event" can sometimes be
    # caused by subtle YAML indentation issues (e.g., tabs instead of spaces).
    # This format ensures the correct structure for an HTTP API event.
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: post

  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
