# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: supermarmot
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-service

provider:
  name: aws
  runtime: nodejs20.x

functions:
  getUser:
    handler: handler.getUser
    events:
    - http:
      path: users/{id}
      method:get

